# Generated by Django 6.0.1 on 2026-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_registration',
            },
        ),
        migrations.CreateModel(
            name='HmsDoctors',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('department', models.CharField(blank=True, max_length=5, null=True)),
                ('avgcontime', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=160, null=True)),
                ('client_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'hms_doctors',
            },
        ),
        migrations.CreateModel(
            name='HmsDoctorstiming',
            fields=[
                ('slno', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('time1', models.TimeField(blank=True, null=True)),
                ('time2', models.TimeField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'hms_doctorstiming',
            },
        ),
        migrations.CreateModel(
            name='Misel',
            fields=[
                ('misel_primary', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('address3', models.CharField(blank=True, max_length=50, null=True)),
                ('tinno', models.CharField(blank=True, max_length=30, null=True)),
                ('client_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'misel',
            },
        ),
    ]
