# Generated by Django 6.0.6 on 2026-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmsdoctors',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hmsdoctorstiming',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='misel',
            name='client_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
