# Generated by Django 6.0.1 on 2026-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_hmsdoctors_client_id_hmsdoctorstiming_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_registration',
            },
        ),
    ]
